# ==============================================================
# Version: v0.1
#
# Author: Thomas "Maaseh" Bonnet
#
# Description:
# Host-specific variables for pve1.
# Values here override group_vars for this host only.
# ==============================================================

---

# proxmox_node_name:    pve1
# proxmox_storage:      local-zfs
# proxmox_bridge:       vmbr0
