# ==============================================================
# Version: v0.2
#
# Author: Thomas "Maaseh" Bonnet
#
# Description:
# Handlers for the common role.
# Restart chrony is triggered when the chrony config changes.
# ==============================================================

---

- name: Restart chrony
  ansible.builtin.service:
    name:  chronyd
    state: restarted

