# ==============================================================
# Version: v0.1
#
# Description:
# Variables applied to all baremetal servers.
# ==============================================================

---

# Disable features that require kernel-level access.
firewall_managed: false
disk_managed:     false

# Python interpreter must be set explicitly as auto-detection
# may fail in unprivileged VMs.
ansible_python_interpreter: /usr/bin/python3

machine_type: baremetal
