# ==============================================================
# Version: v0.1
#
# Description:
# Host-specific variables for hl-mon-01.
# ==============================================================

---

# Grafana admin credentials (values stored in vault.yml)
grafana_admin_user:     admin
grafana_admin_password: "{{ vault_grafana_admin_pass }}"
